### ISSUE TITLE
API 2.0 Compatibility Limitation

### ISSUE THREAD

**Issue by maxedmini** [DealingLace/HDAnywhereMHUB-HA#1]
2024-11-02 15:24:54.526 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hdanywheremhub which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-11-02 15:25:01.311 ERROR (SyncWorker_0) [custom_components.hdanywheremhub.media_player] Error fetching system information: 'show'

I have tried setting up the integration but no luck getting entities to show and this is the only error I receive in the log?
any suggestions 
thanks

**Comment by DealingLace** [comment]
Hi there, I think I see the issue. The integration goes through the list of available inputs and outputs, marked as 'show' from the API. If you haven't set any to 'show' it might be throwing that error. Meaning that you have not hid any sources. Am I correct in my assumptions?

Obviously that is dumb on my part, please find a potential fix in the updated media_player.py :)

If not, I should see this log request more quickly next time.

**Comment by maxedmini** [comment]
ok new error now
it now show 1 entity media_player.hdmi_matrix_unknown

> 2024-11-05 13:13:12.606 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hdanywheremhub which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-11-05 13:13:20.760 INFO (SyncWorker_2) [custom_components.hdanywheremhub] HDAnywhere MHUB component is set up!
2024-11-05 13:13:26.059 DEBUG (SyncWorker_1) [custom_components.hdanywheremhub.media_player] Received system data: {'header': {'version': '2.0'}, 'data': {'io_data': {'input_video': [{'id': 'inputVideo1', 'type': 'hdmi', 'unit_id': 'V1', 'draw': True, 'start_id': '1', 'ports': '4', 'labels': [{'id': 1, 'label': 'Sky+'}, {'id': 2, 'label': 'Apple TV'}, {'id': 3, 'label': 'Xbox'}, {'id': 4, 'label': 'Raspberry pi'}]}], 'input_video_mirror': [], 'output_video': [{'id': 'outputVideo1', 'type': 'hdmi', 'unit_id': 'V1', 'draw': True, 'start_id': 'a', 'ports': '1', 'labels': [{'id': 'a', 'label': 'Video Output (A)'}]}, {'id': 'outputVideo2', 'type': 'hdbaset', 'unit_id': 'V1', 'draw': True, 'start_id': 'b', 'ports': '3', 'labels': [{'id': 'b', 'label': 'Video Output (B)'}, {'id': 'c', 'label': 'Video Output (C)'}, {'id': 'd', 'label': 'Video Output (D)'}]}], 'output_video_mirror': [], 'input_audio': [], 'input_audio_mirror': [], 'output_audio': [], 'output_audio_mirror': [{'id': 'outputAudioMirror1', 'type': 'multiport', 'unit_id': 'V1', 'mirror': ['outputVideo1', 'outputVideo2'], 'draw': True, 'label': 'Audio Output (Mirrored)', 'start_id': 'a', 'ports': '1'}], 'ir': {'backwards': {'draw': True, 'start_id': '1', 'ports': '4'}, 'forwards': {'draw': True, 'start_id': '6', 'ports': '3'}, 'avr': {'draw': True, 'start_id': '9', 'ports': '1'}}}, 'mhub': {'first_boot': True, 'ip_address': '192.168.5.163', 'mhub_firmware': '2.11', 'mhub-os_firmware': '1.21', 'mhub-os_version': '8.11', 'api': '2.0', 'mhub_official_name': 'MHUB (4x3+1)', 'unit_id': 'V1', 'mhub_name': 'HDMI matrix', 'serial_number': ''}, 'stack': {'stack_status': False, 'stack_rank': '', 'stack_master': {}}}}
2024-11-05 13:13:28.327 INFO (SyncWorker_4) [custom_components.hdanywheremhub.media_player] Device state updated: off
2024-11-05 13:13:30.784 WARNING (MainThread) [homeassistant.components.media_player] Setup of media_player platform hdanywheremhub is taking over 10 seconds.
2024-11-05 13:13:31.053 INFO (SyncWorker_0) [custom_components.hdanywheremhub.media_player] Device state updated: off
2024-11-05 13:13:31.057 ERROR (MainThread) [homeassistant.components.media_player] Platform hdanywheremhub does not generate unique IDs. ID HDMI_matrix_192.168.5.163_Unknown already exists - ignoring media_player.hdmi_matrix_unknown

**Comment by maxedmini** [comment]
after playing around I noticed it was looking for start_label for output id but when calling the /data/100 api it was called start_id so I change the code to the following and I now see output A and B but no  C or D
`# Create media player entities for each output
            media_players = []
            for output in outputs:
                output_id = output.get("start_id", "Unknown")`

**Comment by DealingLace** [comment]
Is there no update available for the video matrix? The model (MHUB U (4x3+1) 40) I tested with is running several versions ahead of yours, and the data response format is thus more in accordance with the updated docs. However, I'd definitely look at making a compatible version, if that's not possible.

Your Firmware: 2.11
Mine: 2.63

Your OS Version: 8.11
Mine: 8.29

Edit: It's worse than I thought, the API versions are also mismatched. Are you using the MHUB431U40? It may take a little longer to redo it to comply with the 2.0 API.

**Comment by DealingLace** [comment]
Right... Please find a new branch created for the V2.0 API, I've only really changed the media_player.py file. It shoooould fit. Although I have not tested it.

**Comment by maxedmini** [comment]
still only showing 2 output entities, if I look at the output from the data/100 request there is no start_id for each output,

I guess outputVideo1","type":"hdmi and ports 1 are for the 1 HDMI output
and the other 3 outputs are listed under the outputVideo2","type":"hdbaset ports 3

**Comment by maxedmini** [comment]
```{
   "header":{
      "version":"2.0"
   },
   "data":{
      "io_data":{
         "input_video":[
            {
               "id":"inputVideo1",
               "type":"hdmi",
               "unit_id":"V1",
               "draw":true,
               "start_id":"1",
               "ports":"4",
               "labels":[
                  {
                     "id":1,
                     "label":"Sky+"
                  },
                  {
                     "id":2,
                     "label":"Apple TV"
                  },
                  {
                     "id":3,
                     "label":"Xbox"
                  },
                  {
                     "id":4,
                     "label":"Raspberry pi"
                  }
               ]
            }
         ],
         "input_video_mirror":[
            
         ],
         "output_video":[
            {
               "id":"outputVideo1",
               "type":"hdmi",
               "unit_id":"V1",
               "draw":true,
               "start_id":"a",
               "ports":"1",
               "labels":[
                  {
                     "id":"a",
                     "label":"Video Output (A)"
                  }
               ]
            },
            {
               "id":"outputVideo2",
               "type":"hdbaset",
               "unit_id":"V1",
               "draw":true,
               "start_id":"b",
               "ports":"3",
               "labels":[
                  {
                     "id":"b",
                     "label":"Video Output (B)"
                  },
                  {
                     "id":"c",
                     "label":"Video Output (C)"
                  },
                  {
                     "id":"d",
                     "label":"Video Output (D)"
                  }
               ]
            }
         ],
         "output_video_mirror":[
            
         ],
         "input_audio":[
            
         ],
         "input_audio_mirror":[
            
         ],
         "output_audio":[
            
         ],
         "output_audio_mirror":[
            {
               "id":"outputAudioMirror1",
               "type":"multiport",
               "unit_id":"V1",
               "mirror":[
                  "outputVideo1",
                  "outputVideo2"
               ],
               "draw":true,
               "label":"Audio Output (Mirrored)",
               "start_id":"a",
               "ports":"1"
            }
         ],
         "ir":{
            "backwards":{
               "draw":true,
               "start_id":"1",
               "ports":"4"
            },
            "forwards":{
               "draw":true,
               "start_id":"6",
               "ports":"3"
            },
            "avr":{
               "draw":true,
               "start_id":"9",
               "ports":"1"
            }
         }
      },
      "mhub":{
         "first_boot":true,
         "ip_address":"192.168.5.163",
         "mhub_firmware":"2.11",
         "mhub-os_firmware":"1.21",
         "mhub-os_version":"8.11",
         "api":"2.0",
         "mhub_official_name":"MHUB (4x3+1)",
         "unit_id":"V1",
         "mhub_name":"HDMI matrix",
         "serial_number":"HDA"
      },
      "stack":{
         "stack_status":false,
         "stack_rank":"",
         "stack_master":{
            
         }
      }
   }
}```

**Comment by DealingLace** [comment]
Ah, I see what's happening there, it took each "outputVideo" as a source instead of each individual output. The code now looks at each label, rather than the output categories.

**Comment by DealingLace** [comment]
Please confirm what hardware model you are using as well, including it's update capabilities. Thanks.

**Comment by DealingLace** [comment]
> still only showing 2 output entities, if I look at the output from the data/100 request there is no start_id for each output,
> 
> I guess outputVideo1","type":"hdmi and ports 1 are for the 1 HDMI output and the other 3 outputs are listed under the outputVideo2","type":"hdbaset ports 3

Yeah, I can't believe I let that slip lol, I knew there wasn't a start_id

**Comment by maxedmini** [comment]
Yes that's now showing all 4 outputs, Thanks
after looking through the api documentation is there a way to call the /​api/data/102 no assign the output names to the entities instead of just a, b, c, d

`{
   "header":{
      "version":"2.0"
   },
   "data":[
      {
         "zone_id":"z1",
         "zone_label":"Living Room",
         "outputs":[
            {
               "unit_id":"V1",
               "output_id":"a"
            }
         ]
      },
      {
         "zone_id":"z2",
         "zone_label":"Kitchen",
         "outputs":[
            {
               "unit_id":"V1",
               "output_id":"b"
            }
         ]
      },
      {
         "zone_id":"z3",
         "zone_label":"Thea Room",
         "outputs":[
            {
               "unit_id":"V1",
               "output_id":"c"
            }
         ]
      }
   ]
}`

**Comment by maxedmini** [comment]
> Please confirm what hardware model you are using as well, including it's update capabilities. Thanks.

MHUB (4x3+1)  api: 2.0 SKU: 1.05.904.012.1 Hostname: MHUB431U

**Comment by DealingLace** [comment]
> Yes that's now showing all 4 outputs, Thanks after looking through the api documentation is there a way to call the /​api/data/102 no assign the output names to the entities instead of just a, b, c, d
> 
> `{ "header":{ "version":"2.0" }, "data":[ { "zone_id":"z1", "zone_label":"Living Room", "outputs":[ { "unit_id":"V1", "output_id":"a" } ] }, { "zone_id":"z2", "zone_label":"Kitchen", "outputs":[ { "unit_id":"V1", "output_id":"b" } ] }, { "zone_id":"z3", "zone_label":"Thea Room", "outputs":[ { "unit_id":"V1", "output_id":"c" } ] } ] }`

I'm struggling to find the docs for the 2.0 API... If you have them it would help a lot.
You are right though, it's a definite improvement to be made. I think I'll mark this issue as complete for now though, and open another. If you have any ideas for improvements as well I'm all ears :)

**Comment by DealingLace** [comment]
You'll find the updated code now :)
